package plugin_api

import (
	"github.com/jsimnz/goplugin"
)

const (
	APPLICATION_PLUGIN = goplugin.Type(iota)
)

// My Application plugin interface
//+goplugin
type ApplicationPlugin interface {
	goplugin.Plugin
	// Custom methods
	Name() string
	Compute(int, int) int
}

// AUTO-GENERATED BY GOPLUGIN
// A singleton to implement the ApplicationPlugin interface
type ApplicationPluginFactory struct {
	goplugin.PluginFactory
	// Function for Name method
	NameFn func() string
	// Function for Compute method
	ComputeFn func(int, int) int
}

// AUTO-GENERATED BY GOPLUGIN
// Implements ApplicationPlugin Name method
func (plugin ApplicationPluginFactory) Name() string {
	return plugin.NameFn()
}

// AUTO-GENERATED BY GOPLUGIN
// Implements ApplicationPlugin Compute method
func (plugin ApplicationPluginFactory) Compute(arg1, arg2 int) int {
	return plugin.ComputeFn(arg1, arg2)
}
